//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace at.jku.ssw.Coco.VSPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("at.jku.ssw.Coco.VSPlugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separates alternatives.
        /// </summary>
        internal static string KW_Alternative {
            get {
                return ResourceManager.GetString("KW_Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stands for all characters.
        /// </summary>
        internal static string KW_Any {
            get {
                return ResourceManager.GetString("KW_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the beginning of an attribute delcaration.
        /// </summary>
        internal static string KW_AttributeStart1 {
            get {
                return ResourceManager.GetString("KW_AttributeStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the beginning of an attribute delcaration.
        /// </summary>
        internal static string KW_AttributeStart2 {
            get {
                return ResourceManager.GetString("KW_AttributeStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables creation of character sets.
        /// </summary>
        internal static string KW_Characters {
            get {
                return ResourceManager.GetString("KW_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables comment specification.
        /// </summary>
        internal static string KW_Comments {
            get {
                return ResourceManager.GetString("KW_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the beginning of the Coco Grammar specification (after possible usings).
        /// </summary>
        internal static string KW_Compiler {
            get {
                return ResourceManager.GetString("KW_Compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to define context-dependent tokens.
        /// </summary>
        internal static string KW_Context {
            get {
                return ResourceManager.GetString("KW_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the end of the Coco grammar specification.
        /// </summary>
        internal static string KW_End {
            get {
                return ResourceManager.GetString("KW_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the beginning of the comment.
        /// </summary>
        internal static string KW_From {
            get {
                return ResourceManager.GetString("KW_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to define resolvers.
        /// </summary>
        internal static string KW_If {
            get {
                return ResourceManager.GetString("KW_If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to skip characters in scanner.
        /// </summary>
        internal static string KW_Ignore {
            get {
                return ResourceManager.GetString("KW_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated scanner will be case insensitive with this option.
        /// </summary>
        internal static string KW_IgnoreCase {
            get {
                return ResourceManager.GetString("KW_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks tokens or expressions as repeatable.
        /// </summary>
        internal static string KW_LBrace {
            get {
                return ResourceManager.GetString("KW_LBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks tokens or expressions as optional.
        /// </summary>
        internal static string KW_LBrack {
            get {
                return ResourceManager.GetString("KW_LBrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups tokens or expressions.
        /// </summary>
        internal static string KW_LPar {
            get {
                return ResourceManager.GetString("KW_LPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set operation.
        /// </summary>
        internal static string KW_Minus {
            get {
                return ResourceManager.GetString("KW_Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that this type of comments can be nested.
        /// </summary>
        internal static string KW_Nested {
            get {
                return ResourceManager.GetString("KW_Nested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the end of a tokens, character sets, productions and grammar specification.
        /// </summary>
        internal static string KW_Period {
            get {
                return ResourceManager.GetString("KW_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set operation.
        /// </summary>
        internal static string KW_Plus {
            get {
                return ResourceManager.GetString("KW_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like tokens, can be used anywhere in grammar.
        /// </summary>
        internal static string KW_Pragmas {
            get {
                return ResourceManager.GetString("KW_Pragmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables production specification.
        /// </summary>
        internal static string KW_Productions {
            get {
                return ResourceManager.GetString("KW_Productions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks tokens or expressions as repeatable.
        /// </summary>
        internal static string KW_RBrace {
            get {
                return ResourceManager.GetString("KW_RBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks tokens or expressions as optional.
        /// </summary>
        internal static string KW_RBrack {
            get {
                return ResourceManager.GetString("KW_RBrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups tokens or expressions.
        /// </summary>
        internal static string KW_RPar {
            get {
                return ResourceManager.GetString("KW_RPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens an area for semantic actions.
        /// </summary>
        internal static string KW_SemActionStart {
            get {
                return ResourceManager.GetString("KW_SemActionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies a synchronisation point.
        /// </summary>
        internal static string KW_Sync {
            get {
                return ResourceManager.GetString("KW_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks the end of the comment.
        /// </summary>
        internal static string KW_To {
            get {
                return ResourceManager.GetString("KW_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the definition of character ranges.
        /// </summary>
        internal static string KW_TokenRange {
            get {
                return ResourceManager.GetString("KW_TokenRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables token specification.
        /// </summary>
        internal static string KW_Tokens {
            get {
                return ResourceManager.GetString("KW_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to improve error recovery.
        /// </summary>
        internal static string KW_Weak {
            get {
                return ResourceManager.GetString("KW_Weak", resourceCulture);
            }
        }
    }
}
